<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>$(LibraryTargetFrameworks)</TargetFrameworks>
    <Title>AutoPoco by holonsoft</Title>
    <Description>AutoPoco is a highly configurable framework for the purpose of fluently building readable test data from Plain Old CLR Objects. This is a modernized (i.e. net6 and higher) port of the excellent AutoPoco project which hasn't been maintained since 2014.</Description>
  </PropertyGroup>

</Project>
