// --------------------------------------------------------------------------------------------------------------------
// <copyright file="CtorSource.cs" company="AutoPoco">
//   Microsoft Public License (Ms-PL)
// </copyright>
// --------------------------------------------------------------------------------------------------------------------

using System.Collections.Concurrent;
using System.Reflection;
using holonsoft.AutoPoco.Configuration;
using holonsoft.AutoPoco.Engine;
using holonsoft.AutoPoco.Engine.Interfaces;
using holonsoft.AutoPoco.Util;

namespace holonsoft.AutoPoco.DataSources.Base;

/// <summary>
///   Creates objects through a constructor. Constructor parameters are fed from the registered members with the
///   same name (case-insensitive) and a compatible type, so records and immutable types get their configured
///   values through the constructor. Parameters without a matching member get their declared default value,
///   the default of their value type, or for reference types a value generated by the session.
///   A struct without any configured member stays at its default value.
/// </summary>
/// <typeparam name="T">The type to create</typeparam>
public class CtorSource<T> : DataSourceBase<T>, IMemberBoundFactory {
   private static readonly ConcurrentDictionary<(Type ContextType, Type ParameterType), MethodInfo> _nextMethods = new();

   private readonly bool _pinned;
   private bool _bound;
   private ConstructorInfo? _constructor;
   private ParameterInfo[] _parameters = [];
   private MemberSource?[] _bindings = [];

   /// <summary>
   ///   Picks the constructor from the members bound by the object builder, see <see cref="ConstructorResolver.Resolve" />.
   /// </summary>
   public CtorSource() { }

   /// <summary>
   ///   Uses exactly this constructor.
   /// </summary>
   public CtorSource(ConstructorInfo constructor) {
      ArgumentNullException.ThrowIfNull(constructor);
      _constructor = constructor;
      _parameters = constructor.GetParameters();
      _bindings = new MemberSource?[_parameters.Length];
      _pinned = true;
   }

   /// <summary>
   ///   The constructor in use, null until resolved.
   /// </summary>
   public ConstructorInfo? Constructor => _constructor;

   public IReadOnlyCollection<EngineTypeMember> BindMembers(IReadOnlyList<MemberSource> members) {
      ArgumentNullException.ThrowIfNull(members);
      _bound = true;

      if (!_pinned)
         _constructor = ConstructorResolver.Resolve(typeof(T), members.Select(m => m.Member).ToList());

      if (_constructor == null) {
         _parameters = [];
         _bindings = [];
         return [];
      }

      _parameters = _constructor.GetParameters();
      _bindings = new MemberSource?[_parameters.Length];
      var consumed = new List<EngineTypeMember>();

      for (var i = 0; i < _parameters.Length; i++) {
         var binding = members.FirstOrDefault(m => ConstructorResolver.Matches(_parameters[i], m.Member));
         if (binding == null)
            continue;

         _bindings[i] = binding;
         consumed.Add(binding.Member);
      }

      return consumed;
   }

   protected override T GetNextValue(IGenerationContext? context) {
      if (!_bound)
         BindMembers([]);

      if (_constructor == null) {
         if (typeof(T).IsValueType)
            return default!;

         throw new InvalidOperationException(
            $"Type '{typeof(T).FullName}' has no public constructor, configure a factory with ConstructWith.");
      }

      // a struct without any configured member keeps its default value, its constructors would only get garbage (Guid, DateOnly, ...)
      if (typeof(T).IsValueType && Array.TrueForAll(_bindings, b => b == null))
         return default!;

      var withinLimit = context?.Builders == null || context.Depth < context.Builders.RecursionLimit;
      // the object does not exist yet, the node still lets ParentSource find the enclosing object
      var objectNode = new TypeGenerationContextNode(context?.Node, null);
      var args = new object?[_parameters.Length];

      for (var i = 0; i < _parameters.Length; i++) {
         var binding = _bindings[i];
         args[i] = binding != null && withinLimit && context != null
            ? binding.Source.InternalNext(new GenerationContext(context.Builders, CreateMemberNode(objectNode, binding.Member)))
            : Fallback(_parameters[i], context, withinLimit, objectNode);
      }

      return (T) _constructor.Invoke(args);
   }

   private static IGenerationContextNode CreateMemberNode(TypeGenerationContextNode objectNode, EngineTypeMember member)
      => member switch {
         EngineTypePropertyMember property => new TypePropertyGenerationContextNode(objectNode, property),
         EngineTypeFieldMember field => new TypeFieldGenerationContextNode(objectNode, field),
         _ => objectNode
      };

   private static object? Fallback(ParameterInfo parameter, IGenerationContext? context, bool withinLimit, TypeGenerationContextNode objectNode) {
      if (parameter.HasDefaultValue)
         return parameter.DefaultValue;

      // value types stay at their default: generating e.g. a DateOnly from random ints would throw
      if (parameter.ParameterType.IsValueType)
         return Activator.CreateInstance(parameter.ParameterType);

      if (context == null || !withinLimit)
         return null;

      // ask the session for a value of the parameter type, one level deeper so recursive types hit the recursion limit
      var target = context.Builders == null
         ? context
         : new GenerationContext(context.Builders, objectNode);

      var next = _nextMethods.GetOrAdd((target.GetType(), parameter.ParameterType), key =>
         key.ContextType.GetMethod(nameof(IGenerationContext.Next), Type.EmptyTypes)!.MakeGenericMethod(key.ParameterType));

      return next.Invoke(target, null);
   }
}
